#include "pages.h"

const char *wifi_page =
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
"<title>Konfiguracja WiFi</title>"
"<style>"
"body{"
"margin:0;"
"font-family:Arial,sans-serif;"
"background:#f4f6f9;"
"display:flex;"
"justify-content:center;"
"align-items:center;"
"height:100vh;"
"}"
".card{"
"background:white;"
"padding:30px;"
"border-radius:15px;"
"box-shadow:0 4px 20px rgba(0,0,0,0.15);"
"width:320px;"
"}"
"h1{"
"text-align:center;"
"margin-top:0;"
"color:#333;"
"}"
"label{"
"display:block;"
"margin-top:15px;"
"font-weight:bold;"
"color:#555;"
"}"
"input{"
"width:100%;"
"padding:10px;"
"margin-top:5px;"
"border:1px solid #ccc;"
"border-radius:8px;"
"box-sizing:border-box;"
"}"
"button{"
"width:100%;"
"margin-top:20px;"
"padding:12px;"
"border:none;"
"border-radius:8px;"
"background:#0078ff;"
"color:white;"
"font-size:16px;"
"cursor:pointer;"
"}"
"button:hover{"
"background:#005fd1;"
"}"
".footer{"
"text-align:center;"
"margin-top:15px;"
"font-size:12px;"
"color:#888;"
"}"
"</style>"
"</head>"
"<body>"
"<div class='card'>"
"<h1>ESP32 WiFi</h1>"
"<form action='/save' method='POST'>"
"<label>SSID</label>"
"<input type='text' name='ssid' required>"
"<label>Hasło</label>"
"<input type='password' name='password' required>"
"<button type='submit'>Połącz</button>"
"</form>"
"<div class='footer'>"
"Konfiguracja urządzenia"
"</div>"
"</div>"
"</body>"
"</html>";

const char *control_page =
"<!DOCTYPE html>"
"<html>"
"<body>"
"<h1>Sterowanie LED</h1>"
"<button onclick=\"fetch('/led/on')\">ON</button>"
"<button onclick=\"fetch('/led/off')\">OFF</button>"
"</body>"
"</html>";

const char *camera_page =
"<!DOCTYPE html>"
"<html>"
"<head>"
"<meta charset='utf-8'>"
"<title>ESP32 Camera</title>"
"<style>"
"body{background:#202124;color:white;text-align:center;font-family:Arial;}"
"img{max-width:90%;border-radius:12px;box-shadow:0 0 20px rgba(255,255,255,0.2);}"
"</style>"
"</head>"
"<body>"
"<h1>ESP32 Camera</h1>"
"<img id='cam'>"
"<script>"
"function update(){"
"document.getElementById('cam').src='/capture?t='+Date.now();"
"}"
"setInterval(update,100);"
"update();"
"</script>"
"</body>"
"</html>";